### ISSUE TITLE
Help on how to set this up for at least the basics

### ISSUE THREAD

**Issue by MichaelSDavid** [machinamentum/jai#1]
I know this project is quite old, but I really want to complete the circle with all these new languages focused on game programming. I have Jiyu and Beef working, but I can't get this implementation of Jai working, not even hello world. I can't find the modules, and all the errors are about missing brackets or semicolons which I haven't even seen in examples. I know you got this working somehow since you also have a repository of a game made with your version of Jai. I just want to be able to set this up for basic programming at least. Please and thank you.

I am on Mac OS 10.15.4, although that probably doesn't matter much since this should work the same cross-platform-wise.

**Comment by machinamentum** [comment]
This project was not taken very far. The repository you are referring to was developed using the official version of Jai. I may close/private this project in the near future to avoid confusion.
